### ISSUE TITLE
Some Croatian holidays have different dates in 2020

### ISSUE THREAD

**Issue by sebojanko** [christopherthompson81/pgsql_holidays#1]
Hi,
nice package! I found some wrong data related to my home country, Croatia, so I wanted you to know.

Last year, the government decided to change some state holidays - https://publicholidays.com.hr/2020-dates/
For fixing this issue, the holiday on the 25th of June should be deleted and a new one should be added on the 18th of November. This one should be named 'Dan sjećanja'.

Keep up the good work!

**Comment by christopherthompson81** [comment]
Thank you for the feedback! I'll try to get a fix out shortly.

**Comment by christopherthompson81** [comment]
Was this change made by proclamation for a single year, or is it a legislative rule change that also affects future years? If it's the second type, do you know of a site that lists the rules or publishes the new rules?

**Comment by sebojanko** [comment]
It's a permanent change.
The best source in English I've found is Wikipedia - https://en.wikipedia.org/wiki/Public_holidays_in_Croatia
The listed reference is official, but it's in Croatian. Under 'Članak 1' (Article 1) is the list of holidays. Since there's no English translation of the law, your best bet is Wikipedia or some other English pages.

**Comment by christopherthompson81** [comment]
OK, I consider the commit to have addressed this.
