### ISSUE TITLE
How about shortened days?

### ISSUE THREAD

**Issue by anttilinno** [christopherthompson81/pgsql_holidays#3]
Is this a straight port from python or features go into this repo? I miss the shortened days that come before holidays.
For example, in Estonia, 23. december is shortened workday (-3 hours). In Latvia the workday is shortened by 1 hour, with complicated rules.
If I submit PR with Estonian shortened days, could this be of benefit to others? And maybe other countries will follow my lead :)

**Comment by christopherthompson81** [comment]
I'm always willing to review PRs!

Javascript has a library that supports that kind of feature here - https://github.com/commenthol/date-holidays

I've been thinking about how to merge the ideas from there into here, but haven't finished that yet. I should have a complex return type that has non-standard periods identified at some point though.

**Comment by christopherthompson81** [comment]
Is this link a satisfactory source to reference about work day shortening in Estonia?

https://www.tooelu.ee/en/Employee/Working-relations/Working-time-and-rest-period/Shortening-Working-Time-Before-National-and-State-Holidays

**Comment by christopherthompson81** [comment]
Shortened days have been implemented in Estonia (and throughout the package). fixes are likely necessary, but the feature is not thoroughly supported. Closing.
